[pytest]
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    gui: marks tests as gui tests (require Qt/PySide2 environment)
    gui_qml: marks tests requiring QGuiApplication + QQmlApplicationEngine (skip on headless CI)
testpaths = tests
filterwarnings =
    ignore:Benchmarks are automatically disabled because xdist plugin is active:pytest_benchmark.logger.PytestBenchmarkWarning
